version: '3'

services:
  sandbox:
    image: joncatlin/pentaho-client
    # volumes:
    #   - ./shared:/home/sandbox/shared
    ports:
      # VNC GUI client port
      - 5900:5900
      # Web GUI client port
      - 6080:80
    environment:
      - VNC_PASSWORD=password
      - HTTP_PASSWORD=password
      - USER=sandbox
      - PASSWORD=password
      - RESOLUTION=1920x1080
    volumes:
      - ./input:/input
      - ./output:/output
      - ./processed:/processed
    networks:
      - pentaho

networks:
  pentaho:
